apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "twbc-nft-admin-portal.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/tls-acme: "true"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    {{- include "twbc-nft-admin-portal.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ include "twbc-nft-admin-portal.fullname" . }}-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name:  {{ include "twbc-nft-admin-portal.fullname" . }}
          #       port:
          #         number: {{ .Values.service.port }}
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: twbc-nft-api-service
                port: 
                  number: 3000
