apiVersion: v1
kind: Service
metadata:
  name: {{ include "twbc-nft-admin-portal.fullname" . }}
  labels: {{- include "twbc-nft-admin-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "twbc-nft-admin-portal.selectorLabels" . | nindent 4 }}
